/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contactapp;

import java.sql.*;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author vishnu
 */
public class User extends javax.swing.JFrame {

    /**nu
     * Creates new form User
     */
    String name1=Home.name_n;
    String num_n=Home.num;
    String oldnum=" ";
    DefaultTableModel model1;
     Util util;
    
    public void setTable() throws SQLException
    {
        try{
           
            PreparedStatement ps=util.createPST("SELECT * FROM CONTACT1 WHERE NUM=?");
            ps.setString(1,num_n);
            ResultSet rs=util.select(ps);
            model1=(DefaultTableModel) table_contact.getModel();
            model1.setRowCount(0);
            while(rs.next()){
                model1.insertRow(model1.getRowCount(),new Object[]{rs.getString("NAME"),rs.getString("ID"),rs.getString("CONTACT_NUM")});
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
      //  return null;
    }
    public User() {
        util=new Util();
        initComponents();
       
        try{
           setTable();  
         }
        catch(Exception e){
            e.printStackTrace();
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_contact = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SEARCH");

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel2.setText("CONTACT NAME");

        jLabel3.setText("CONTACT NUMBER");

        jLabel4.setText("CONTACT EMAIL");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contactapp/newpackage/download.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        table_contact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CONTACT NAME", "CONTA T EMAIL", "CONTACT NUMBER"
            }
        ));
        table_contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_contactMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_contact);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name)
                    .addComponent(number)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(add)
                        .addGap(35, 35, 35)
                        .addComponent(edit)
                        .addGap(41, 41, 41)
                        .addComponent(delete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add)
                            .addComponent(edit)
                            .addComponent(delete)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(126, 126, 126))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
         String edit="";
         num_n=Home.num;
        boolean flag = false;
        try
        {
        edit = String.valueOf(model1.getValueAt(table_contact.getSelectedRow(),1));
    }//GEN-LAST:event_editActionPerformed
        catch(ArrayIndexOutOfBoundsException ae)
        {
            dialog.showMessageDialog(null, "You have not selected any contact.");
           // setTable();
            flag=true;
        }
        if(flag==false)
        {
             int result = dialog.showConfirmDialog(null, "Are you sure you want to edit this contact ?");
        if (result == dialog.YES_OPTION) {
            try {
               // Util util=new Util();
System.out.println("helo"+oldnum);
                PreparedStatement ps = util.createPST("UPDATE CONTACT1 SET CONTACT_NUM = ? ,NAME = ? , ID = ? WHERE NUM = ? AND CONTACT_NUM = ?");
                ps.setString(1, number.getText());
                ps.setString(2, name.getText());
                ps.setString(3, email.getText());
                ps.setString(4, num_n);
                ps.setString(5, oldnum);
                util.modify(ps);

                setTable();
            } catch (Exception e) {

                e.printStackTrace();
            }
        }
       
        }
    }
    private void table_contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_contactMouseClicked
        // TODO add your handling code here:
        name.setText(String.valueOf(model1.getValueAt(table_contact.getSelectedRow(),0)));
        number.setText(String.valueOf(model1.getValueAt(table_contact.getSelectedRow(),2)));
        email.setText(String.valueOf(model1.getValueAt(table_contact.getSelectedRow(),1)));
        oldnum = model1.getValueAt(table_contact.getSelectedRow(), 2).toString();
    }//GEN-LAST:event_table_contactMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try {
          //  Util util=new Util();
           // System.out.println("haiiiiii"+num_n);
           num_n=Home.num;
            PreparedStatement ps = util.createPST("INSERT INTO CONTACT1 VALUES(?,?,?,?)");
            ps.setString(3, num_n);
            ps.setString(4, number.getText());
            ps.setString(1, name.getText());
            ps.setString(2, email.getText());
            util.modify(ps);

            setTable();
        } catch (Exception e) {
            dialog.showMessageDialog(null, "This contact already exists in your address book.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String no_to_delete="";
        boolean flag = false;
        try{
        no_to_delete =number.getText().toString();
        }
        catch(ArrayIndexOutOfBoundsException ae)
        {
            dialog.showMessageDialog(null, "You have not selected any contact.");
            setTable();
            flag = true;

        }
        if(flag==false)
        {
        int result = dialog.showConfirmDialog(null, "Are you sure you want to delete this contact?");
        if (result == dialog.YES_OPTION) {

            try {
                Util util=new Util();
                PreparedStatement ps = util.createPST("DELETE FROM CONTACT1 WHERE NUM = ? AND CONTACT_NUM = ?");
                ps.setString(1, num_n);
                ps.setString(2, no_to_delete);

                util.modify(ps);

                setTable();

            }

            catch (Exception e) {
                 dialog.showMessageDialog(null, "Deletion is unsuccesfull");
                e.printStackTrace();
            }
        }

       
        }
    }//GEN-LAST:event_deleteActionPerformed
        
    
     
     


            
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JOptionPane dialog;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JTextField search;
    private javax.swing.JTable table_contact;
    // End of variables declaration//GEN-END:variables
}
